---
title: "hydroids2024"
author: "Marina Schnell"
date: "2024-09-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages}
library(tidyverse)
library(readxl)
library(forcats)
library(FSA)

se <- function(x) sd(x)/sqrt(length(x))
```

```{r load-data}
hydroids <- read_xlsx("data/NeCSA24miscellanea.xlsx", sheet = "data")
```

```{r expand-and-join}

exp_hydroids <- expand(hydroids,
                       tide_ht,
                       number,
                       species) %>%
  left_join(hydroids,
            by = join_by(tide_ht, number, species)) %>%
  mutate(subquadrats = as.numeric(subquadrats)) %>%
  mutate(subquadrats = replace_na(subquadrats, 0)) %>%
  mutate(proportion = subquadrats/25) %>%
  filter(!(tide_ht == "L" & number == 3)
         & !(tide_ht == "L" & number == 4)
         & !(tide_ht == "L" & number == 6)) %>%
  mutate(tide_ht = factor(tide_ht)) %>%
  mutate(tide_ht = fct_relevel(tide_ht, c("L", "M", "H")))

```

```{r hydroid-plot-proportion}

# error bars represent +/- 1 standard error

exp_hydroids %>%
  filter(species %in% c("Clava_multicornis",
                        "Dynamena_pumila",
                        "Laomedea_flexuosa",
                        "Sertularella_rugosa")) %>%
  group_by(tide_ht, species) %>%
  mutate(proportion = as.numeric(subquadrats)/25) %>%
  summarise(mean_prop = mean(proportion),
            se_prop = se(proportion)) %>%
  mutate(ymin_prop = mean_prop - se_prop) %>%
  mutate(ymin_prop = case_when(ymin_prop < 0 ~ 0,
                          TRUE ~ ymin_prop)) %>%
  mutate(ymax_prop = mean_prop + se_prop) %>% 
  ggplot(mapping = aes(tide_ht, mean_prop, fill = species)) +
  geom_col(position = "dodge") +
  scale_fill_viridis_d() +
  geom_errorbar(aes(ymin = ymin_prop, ymax = ymax_prop),
                width=.3,
                position = position_dodge(.9)) +
  labs(x = "Tide Height",
       y = "Mean Proportion")
  
```

```{r hydroid-plot-mean-number}
exp_hydroids %>%
  filter(species %in% c("Clava_multicornis",
                        "Dynamena_pumila",
                        "Laomedea_flexuosa",
                        "Sertularella_rugosa")) %>%
  group_by(tide_ht, species) %>%
  summarise(mean_num = mean(subquadrats),
            se_num = se(subquadrats)) %>%
  mutate(ymin_num = mean_num - se_num) %>%
  mutate(ymin_num = case_when(ymin_num < 0 ~ 0,
                          TRUE ~ ymin_num)) %>%
  mutate(ymax_num = mean_num + se_num) %>% 
  mutate(tide_ht_2 = case_when(tide_ht == "L" ~ "Low",
                               tide_ht == "M" ~ "Mid",
                               tide_ht == "H" ~ "High")) %>%
  mutate(tide_ht_2 = factor(tide_ht_2)) %>%
  mutate(tide_ht_2 = fct_relevel(tide_ht_2, c("Low", "Mid", "High"))) %>%
  ggplot(mapping = aes(tide_ht_2, mean_num, fill = species)) +
  geom_col(position = "dodge") +
  scale_fill_viridis_d() +
  geom_errorbar(aes(ymin = ymin_num, ymax = ymax_num),
                width=.3,
                position = position_dodge(.9)) +
  labs(x = "Tide Height",
       y = "Mean Number of Quadrats (out of 25)",
       title = "Presence of Hydroids in 2024 NeCSA Survey",
       fill = "Species") +
  scale_fill_manual(labels = c("Clava_multicornis" = "Clava multicornis",
                               "Dynamena_pumila" = "Dynamena pumila",
                               "Laomedea_flexuosa" = "Laomedea flexuosa",
                               "Sertularella_rugosa" = "Sertularella rugosa"),
                       values = c("Clava_multicornis" = "#A4B9D2",
                                  "Dynamena_pumila" = "#375A63",
                                  "Laomedea_flexuosa" = "#946DB7",
                                  "Sertularella_rugosa" = "#AE875B")) +
  theme(legend.text = element_text(face="italic")) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 8, b = 0, l = 0))) +
  theme(axis.title.x = element_text(margin = margin(t = 8, r = 0, b = 0, l = 0))) +
  ylim(0,25)

```

```{r hydroid-plot-total}
exp_hydroids %>%
  filter(species %in% c("Clava_multicornis",
                        "Dynamena_pumila",
                        "Laomedea_flexuosa",
                        "Sertularella_rugosa")) %>%
  group_by(tide_ht, species) %>%
  summarise(sum_subquadrats = sum(subquadrats)) %>%
  ggplot(mapping = aes(tide_ht, sum_subquadrats, fill = species)) +
  geom_col(position = "dodge") +
  scale_fill_viridis_d()
```

```{r KW-test-dyna_p}

dyna_p <- exp_hydroids %>%
  filter(species == "Dynamena_pumila")

kruskal.test(proportion ~ tide_ht, data = dyna_p)

dunnTest(dyna_p$proportion ~ dyna_p$tide_ht, method = "bh")
```

```{r KW-test-dyna_p}

laom_f <- exp_hydroids %>%
  filter(species == "Laomedea_flexuosa")

kruskal.test(proportion ~ tide_ht, data = laom_f)

dunnTest(laom_f$proportion ~ laom_f$tide_ht, method = "bh")
```
